name: Deploy Docs to Doc (Staging)

on:
  push:
    branches:
      - main

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  BuildAndMakeLive:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo
      uses: actions/checkout@v2

    - name: Install docusaurus
      run: yarn install

    - name: Build docusaurus
      run: yarn build
      env:
        # Workaround for https://github.com/webpack/webpack/issues/14532
        # See also https://github.com/facebook/docusaurus/issues/5778
        NODE_OPTIONS: "--openssl-legacy-provider"

    - name: Send build to doc
      uses: appleboy/scp-action@master
      with:
        host: doc.net.fourieraudio.com
        username: fourier
        port: 22
        key: ${{ secrets.SSH_DOC_FOURIER }}
        source: "/home/runner/work/pascal/pascal/build"
        target: "/home/fourier"

    - name: Copy to live docusaurus docusaurus directory
      uses: appleboy/ssh-action@master
      with:
        host: doc.net.fourieraudio.com
        username: fourier
        key: ${{ secrets.SSH_DOC_FOURIER }}
        port: 22
        script: |
          sudo cp -r /home/fourier/github/workspace/build/* /var/www/docusaurus_staging/live
