name: Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 46.101.58.33
        username: root
        password: ${{ secrets.MARTY_ROOT }}
        port: 22
        script: |
          cd /var/www/docusaurus/docs
          ls
