
name: Deploy Docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo
      uses: actions/checkout@v2

    - name: Install docusaurus
      run: yarn install

    - name: Build docusaurus
      run: yarn build

    - name: Package docusaurus build
      run: ls

    # - name: Send build to marty
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: 46.101.58.33
    #     username: fourier
    #     port: 22
    #     key: ${{ secrets.SSH_MARTY_FOURIER }}
    #     source: "build.tar.gz"
    #     target: "/var/www/docusaurus"
